### ISSUE TITLE
Terraform 0.13 Support - Version Inconsistency

### ISSUE THREAD

**Issue by MatthiasScholzTW** [avinor/tau#33]
# Overview

The documentation states terraform a required terraform version >=0.13 but the implementation is bound to 0.12.

# Expectation

The minimum required version requirement is consistent.

# References

## README.md

_1. Tau requires [terraform](https://www.terraform.io/) 0.13+_

## Version Check

https://github.com/avinor/tau/blob/f003d3c529e6f1ec9db3d27646b0b9c4bd37f2c9/pkg/terraform/engine.go#L43

**Comment by yngveh** [comment]
God observation.

We will create a PR that have terraform 0.12+ support in README for now.
